// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NgsildEntity.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "NgsildEntity.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




NgsildEntity::NgsildEntity()
{
}

NgsildEntity::~NgsildEntity()
{
}

NgsildEntity::NgsildEntity(
        const NgsildEntity& x)
{
    m_id = x.m_id;
    m_type = x.m_type;
}

NgsildEntity::NgsildEntity(
        NgsildEntity&& x) noexcept
{
    m_id = std::move(x.m_id);
    m_type = std::move(x.m_type);
}

NgsildEntity& NgsildEntity::operator =(
        const NgsildEntity& x)
{

    m_id = x.m_id;
    m_type = x.m_type;
    return *this;
}

NgsildEntity& NgsildEntity::operator =(
        NgsildEntity&& x) noexcept
{

    m_id = std::move(x.m_id);
    m_type = std::move(x.m_type);
    return *this;
}

bool NgsildEntity::operator ==(
        const NgsildEntity& x) const
{
    return (m_id == x.m_id &&
           m_type == x.m_type);
}

bool NgsildEntity::operator !=(
        const NgsildEntity& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member id
 * @param _id New value to be copied in member id
 */
void NgsildEntity::id(
        const std::string& _id)
{
    m_id = _id;
}

/*!
 * @brief This function moves the value in member id
 * @param _id New value to be moved in member id
 */
void NgsildEntity::id(
        std::string&& _id)
{
    m_id = std::move(_id);
}

/*!
 * @brief This function returns a constant reference to member id
 * @return Constant reference to member id
 */
const std::string& NgsildEntity::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
std::string& NgsildEntity::id()
{
    return m_id;
}


/*!
 * @brief This function copies the value in member type
 * @param _type New value to be copied in member type
 */
void NgsildEntity::type(
        const std::string& _type)
{
    m_type = _type;
}

/*!
 * @brief This function moves the value in member type
 * @param _type New value to be moved in member type
 */
void NgsildEntity::type(
        std::string&& _type)
{
    m_type = std::move(_type);
}

/*!
 * @brief This function returns a constant reference to member type
 * @return Constant reference to member type
 */
const std::string& NgsildEntity::type() const
{
    return m_type;
}

/*!
 * @brief This function returns a reference to member type
 * @return Reference to member type
 */
std::string& NgsildEntity::type()
{
    return m_type;
}


// Include auxiliary functions like for serializing/deserializing.
#include "NgsildEntityCdrAux.ipp"

