// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NgsildEntity.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_NGSILDENTITY_H_
#define _FAST_DDS_GENERATED_NGSILDENTITY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(NGSILDENTITY_SOURCE)
#define NGSILDENTITY_DllAPI __declspec( dllexport )
#else
#define NGSILDENTITY_DllAPI __declspec( dllimport )
#endif // NGSILDENTITY_SOURCE
#else
#define NGSILDENTITY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define NGSILDENTITY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure NgsildEntity defined by the user in the IDL file.
 * @ingroup NgsildEntity
 */
class NgsildEntity
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport NgsildEntity();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~NgsildEntity();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object NgsildEntity that will be copied.
     */
    eProsima_user_DllExport NgsildEntity(
            const NgsildEntity& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object NgsildEntity that will be copied.
     */
    eProsima_user_DllExport NgsildEntity(
            NgsildEntity&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object NgsildEntity that will be copied.
     */
    eProsima_user_DllExport NgsildEntity& operator =(
            const NgsildEntity& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object NgsildEntity that will be copied.
     */
    eProsima_user_DllExport NgsildEntity& operator =(
            NgsildEntity&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x NgsildEntity object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const NgsildEntity& x) const;

    /*!
     * @brief Comparison operator.
     * @param x NgsildEntity object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const NgsildEntity& x) const;

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const std::string& _id);

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            std::string&& _id);

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const std::string& id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport std::string& id();


    /*!
     * @brief This function copies the value in member type
     * @param _type New value to be copied in member type
     */
    eProsima_user_DllExport void type(
            const std::string& _type);

    /*!
     * @brief This function moves the value in member type
     * @param _type New value to be moved in member type
     */
    eProsima_user_DllExport void type(
            std::string&& _type);

    /*!
     * @brief This function returns a constant reference to member type
     * @return Constant reference to member type
     */
    eProsima_user_DllExport const std::string& type() const;

    /*!
     * @brief This function returns a reference to member type
     * @return Reference to member type
     */
    eProsima_user_DllExport std::string& type();

private:

    std::string m_id;
    std::string m_type;

};

#endif // _FAST_DDS_GENERATED_NGSILDENTITY_H_



